project:
  title: "walker.data.com"
  # https://quarto.org/docs/reference/projects/options.html
  # website, book, or manuscript
  type: website # default?
  # force Quarto command line execution rel to command line folder
  #   i.e. specify working dir for rendering files within project
  #   e.g. when running background job in Rstudio
  #   default: working dir is dir of qmd file itself e.g. ./inst/qmd/
  # execute-dir: project
  # resources:
  #   - data/*.parquet
  # output-dir: _output
  # preview:
  #   port: 4200
  #   browser: false
# # default options per page - may/may not include webR
# webr:
#   show-startup-message: false    # Disable displaying status of webR initialization
#   packages: ['ggplot2', 'dplyr'] # Install R packages on document open
#
# # Attach webR extension for the project
# filters:
#   - webr


